Updates to make repository public
CQCL/pytket-benchmarking-store pull request #11
Opened 2024-04-12 18:57 UTC by daniel-mills-cqc

Just a couple of small things before making the repository public.
Mostly navigating around the fact that this repo is public but pytket-benchmarking is not.

2024-04-30 09:47 UTC, sjdilkes requested changes
just a couple of typos!

2024-04-30 09:47 UTC, sjdilkes commented on README.md
> +    It must also include atleast the columns: 'name', containing the name of the ciruit; 'width', containing the number of qubits in the circuit; and 'label', containing an additional label describin
```suggestion
    It must also include at least the columns: 'name', containing the name of the circuit; 'width', containing the number of qubits in the circuit; and 'label', containing an additional label describing the class of circuits that the circuit belongs to.
```

2024-04-30 12:20 UTC, daniel-mills-cqc commented on README.md
> +    It must also include atleast the columns: 'name', containing the name of the ciruit; 'width', containing the number of qubits in the circuit; and 'label', containing an additional label describin
Aha, thanks!

2024-05-02 15:38 UTC, sjdilkes approved these changes

2024-05-02 15:44 UTC, merged